export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const USER_LOGOUT = 'USER_LOGOUT';
export const SET_AUTH_HEADER = 'SET_AUTH_HEADER';

export const GET_FORMS = 'GET_FORMS';
export const GET_FORM = 'GET_FORM';
export const DELETE_FORM = 'DELETE_FORM';
export const UPDATE_FORM = 'UPDATE_FORM';
export const FETCHING_FORMS = 'FETCHING_FORMS';
export const UPDATE_NEW_FORM = 'UPDATE_NEW_FORM';
export const ADD_NEW_FORM = 'ADD_NEW_FORM';
export const UPDATE_EXSITING_FORM = 'UPDATE_EXSITING_FORM';

export const SUCCESS_NOTIFICATION = 'SUCCESS_NOTIFICATION';
export const ERROR_NOTIFICATION = 'ERROR_NOTIFICATION';

export const FETCHING_RESPONSE = 'FETCHING_RESPONSE';
export const SUBMIT_FORM = 'SUBMIT_FORM';
export const FETCH_RESPONSES = 'FETCH_RESPONSES';
export const FETCH_RESPONSE = 'FETCH_RESPONSE';
